# Generated by Django 3.2.3 on 2021-05-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('des', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
